apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cyderes
  name: cyderes
spec:
  containers:
  - image: nginx
    name: cyderes
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
