apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: cyderes
  name: cyderes
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: cyderes
  type: NodePort
status:
  loadBalancer: {}
